package io.wumf.wumf;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by max on 13.07.16.
 */
public class CountriesCodes {
    public static Map<String, String> map = new HashMap<>();
    static {
        map.put("AF", "Afghanistan");
        map.put("AFG", "Afghanistan");
        map.put("AL", "Albania");
        map.put("ALB", "Albania");
        map.put("DZ", "Algeria");
        map.put("DZA", "Algeria");
        map.put("AS", "American");
        map.put("ASM", "American");
        map.put("AD", "Andorra");
        map.put("AND", "Andorra");
        map.put("AO", "Angola");
        map.put("AGO", "Angola");
        map.put("AI", "Anguilla");
        map.put("AIA", "Anguilla");
        map.put("AQ", "Antarctica");
        map.put("ATA", "Antarctica");
        map.put("AG", "Antigua");
        map.put("ATG", "Antigua");
        map.put("AR", "Argentina");
        map.put("ARG", "Argentina");
        map.put("AM", "Armenia");
        map.put("ARM", "Armenia");
        map.put("AW", "Aruba");
        map.put("ABW", "Aruba");
        map.put("AU", "Australia");
        map.put("AUS", "Australia");
        map.put("AT", "Austria");
        map.put("AUT", "Austria");
        map.put("AZ", "Azerbaijan");
        map.put("AZE", "Azerbaijan");
        map.put("BS", "Bahamas");
        map.put("BHS", "Bahamas");
        map.put("BH", "Bahrain");
        map.put("BHR", "Bahrain");
        map.put("BD", "Bangladesh");
        map.put("BGD", "Bangladesh");
        map.put("BB", "Barbados");
        map.put("BRB", "Barbados");
        map.put("BY", "Belarus");
        map.put("BLR", "Belarus");
        map.put("BE", "Belgium");
        map.put("BEL", "Belgium");
        map.put("BZ", "Belize");
        map.put("BLZ", "Belize");
        map.put("BJ", "Benin");
        map.put("BEN", "Benin");
        map.put("BM", "Bermuda");
        map.put("BMU", "Bermuda");
        map.put("BT", "Bhutan");
        map.put("BTN", "Bhutan");
        map.put("BO", "Bolivia");
        map.put("BOL", "Bolivia");
        map.put("BA", "Bosnia and Herzegovina");
        map.put("BIH", "Bosnia and Herzegovina");
        map.put("BW", "Botswana");
        map.put("BWA", "Botswana");
        map.put("BR", "Brazil");
        map.put("BRA", "Brazil");
        map.put("IO", "British Indian Ocean Territory");
        map.put("IOT", "British Indian Ocean Territory");
        map.put("VG", "British Virgin Islands");
        map.put("VGB", "British Virgin Islands");
        map.put("BN", "Brunei");
        map.put("BRN", "Brunei");
        map.put("BG", "Bulgaria");
        map.put("BGR", "Bulgaria");
        map.put("BF", "Burkina Faso");
        map.put("BFA", "Burkina Faso");
        map.put("BI", "Burundi");
        map.put("BDI", "Burundi");
        map.put("KH", "Cambodia");
        map.put("KHM", "Cambodia");
        map.put("CM", "Cameroon");
        map.put("CMR", "Cameroon");
        map.put("CA", "Canada");
        map.put("CAN", "Canada");
        map.put("CV", "Cape Verde");
        map.put("CPV", "Cape Verde");
        map.put("KY", "Cayman Islands");
        map.put("CYM", "Cayman Islands");
        map.put("CF", "Central African Republic");
        map.put("CAF", "Central African Republic");
        map.put("TD", "Chad");
        map.put("TCD", "Chad");
        map.put("CL", "Chile");
        map.put("CHL", "Chile");
        map.put("CN", "China");
        map.put("CHN", "China");
        map.put("CX", "Christmas Island");
        map.put("CXR", "Christmas Island");
        map.put("CC", "Cocos Islands");
        map.put("CCK", "Cocos Islands");
        map.put("CO", "Colombia");
        map.put("COL", "Colombia");
        map.put("CO", "Colombia");
        map.put("COL", "Colombia");
        map.put("KM", "Comoros");
        map.put("COM", "Comoros");
        map.put("CK", "Cook Islands");
        map.put("COK", "Cook Islands");
        map.put("CR", "Costa Rica");
        map.put("CRI", "Costa Rica");
        map.put("HR", "Croatia");
        map.put("HRV", "Croatia");
        map.put("CU", "Cuba");
        map.put("CUB", "Cuba");
        map.put("CW", "Curacao");
        map.put("CUW", "Curacao");
        map.put("CY", "Cyprus");
        map.put("CYP", "Cyprus");
        map.put("CZ", "Czech Republic");
        map.put("CZE", "Czech Republic");
        map.put("CD", "Democratic Republic of the Congo");
        map.put("COD", "Democratic Republic of the Congo");
        map.put("DK", "Denmark");
        map.put("DNK", "Denmark");
        map.put("DJ", "Djibouti");
        map.put("DJI", "Djibouti");
        map.put("DM", "Dominica");
        map.put("DMA", "Dominica");
        map.put("DO", "Dominican Republic");
        map.put("DOM", "Dominican Republic");
        map.put("TL", "East Timor");
        map.put("TLS", "East Timor");
        map.put("EC", "Ecuador");
        map.put("ECU", "Ecuador");
        map.put("EG", "Egypt");
        map.put("EGY", "Egypt");
        map.put("SV", "El Salvador");
        map.put("SLV", "El Salvador");
        map.put("GQ", "Equatorial Guinea");
        map.put("GNQ", "Equatorial Guinea");
        map.put("ER", "Eritrea");
        map.put("ERI", "Eritrea");
        map.put("EE", "Estonia");
        map.put("EST", "Estonia");
        map.put("ET", "Ethiopia");
        map.put("ETH", "Ethiopia");
        map.put("FK", "Falkland Islands");
        map.put("FLK", "Falkland Islands");
        map.put("FO", "Faroe Islands");
        map.put("FRO", "Faroe Islands");
        map.put("FJ", "Fiji");
        map.put("FJI", "Fiji");
        map.put("FI", "Finland");
        map.put("FIN", "Finland");
        map.put("FR", "France");
        map.put("FRA", "France");
        map.put("PF", "French Polynesia");
        map.put("PYF", "French Polynesia");
        map.put("GA", "Gabon");
        map.put("GAB", "Gabon");
        map.put("GM", "Gambia");
        map.put("GMB", "Gambia");
        map.put("GE", "Georgia");
        map.put("GEO", "Georgia");
        map.put("DE", "Germany");
        map.put("DEU", "Germany");
        map.put("GH", "Ghana");
        map.put("GHA", "Ghana");
        map.put("GI", "Gibraltar");
        map.put("GIB", "Gibraltar");
        map.put("GR", "Greece");
        map.put("GRC", "Greece");
        map.put("GL", "Greenland");
        map.put("GRL", "Greenland");
        map.put("GD", "Grenada");
        map.put("GRD", "Grenada");
        map.put("GU", "Guam");
        map.put("GUM", "Guam");
        map.put("GT", "Guatemala");
        map.put("GTM", "Guatemala");
        map.put("GG", "Guernsey");
        map.put("GGY", "Guernsey");
        map.put("GN", "Guinea");
        map.put("GIN", "Guinea");
        map.put("GW", "Guinea-Bissau");
        map.put("GNB", "Guinea-Bissau");
        map.put("GY", "Guyana");
        map.put("GUY", "Guyana");
        map.put("HT", "Haiti");
        map.put("HTI", "Haiti");
        map.put("HN", "Honduras");
        map.put("HND", "Honduras");
        map.put("HK", "Hong Kong");
        map.put("HKG", "Hong Kong");
        map.put("HU", "Hungary");
        map.put("HUN", "Hungary");
        map.put("IS", "Iceland");
        map.put("ISL", "Iceland");
        map.put("IN", "India");
        map.put("IND", "India");
        map.put("ID", "Indonesia");
        map.put("IDN", "Indonesia");
        map.put("IR", "Iran");
        map.put("IRN", "Iran");
        map.put("IQ", "Iraq");
        map.put("IRQ", "Iraq");
        map.put("IE", "Ireland");
        map.put("IRL", "Ireland");
        map.put("IM", "Isle of Man");
        map.put("IMN", "Isle of Man");
        map.put("IL", "Israel");
        map.put("ISR", "Israel");
        map.put("IT", "Italy");
        map.put("ITA", "Italy");
        map.put("CI", "Ivory Coast");
        map.put("CIV", "Ivory Coast");
        map.put("JM", "Jamaica");
        map.put("JAM", "Jamaica");
        map.put("JP", "Japan");
        map.put("JPN", "Japan");
        map.put("JE", "Jersey");
        map.put("JEY", "Jersey");
        map.put("JO", "Jordan");
        map.put("JOR", "Jordan");
        map.put("KZ", "Kazakhstan");
        map.put("KAZ", "Kazakhstan");
        map.put("KE", "Kenya");
        map.put("KEN", "Kenya");
        map.put("KI", "Kiribati");
        map.put("KIR", "Kiribati");
        map.put("XK", "Kosovo");
        map.put("XKX", "Kosovo");
        map.put("KW", "Kuwait");
        map.put("KWT", "Kuwait");
        map.put("KG", "Kyrgyzstan");
        map.put("KGZ", "Kyrgyzstan");
        map.put("LA", "Laos");
        map.put("LAO", "Laos");
        map.put("LV", "Latvia");
        map.put("LVA", "Latvia");
        map.put("LB", "Lebanon");
        map.put("LBN", "Lebanon");
        map.put("LS", "Lesotho");
        map.put("LSO", "Lesotho");
        map.put("LR", "Liberia");
        map.put("LBR", "Liberia");
        map.put("LY", "Libya");
        map.put("LBY", "Libya");
        map.put("LI", "Liechtenstein");
        map.put("LIE", "Liechtenstein");
        map.put("LT", "Lithuania");
        map.put("LTU", "Lithuania");
        map.put("LU", "Luxembourg");
        map.put("LUX", "Luxembourg");
        map.put("MO", "Macau");
        map.put("MAC", "Macau");
        map.put("MK", "Macedonia");
        map.put("MKD", "Macedonia");
        map.put("MG", "Madagascar");
        map.put("MDG", "Madagascar");
        map.put("MW", "Malawi");
        map.put("MWI", "Malawi");
        map.put("MY", "Malaysia");
        map.put("MYS", "Malaysia");
        map.put("MV", "Maldives");
        map.put("MDV", "Maldives");
        map.put("ML", "Mali");
        map.put("MLI", "Mali");
        map.put("MT", "Malta");
        map.put("MLT", "Malta");
        map.put("MH", "Marshall Islands");
        map.put("MHL", "Marshall Islands");
        map.put("MR", "Mauritania");
        map.put("MRT", "Mauritania");
        map.put("MU", "Mauritius");
        map.put("MUS", "Mauritius");
        map.put("YT", "Mayotte");
        map.put("MYT", "Mayotte");
        map.put("MX", "Mexico");
        map.put("MEX", "Mexico");
        map.put("FM", "Micronesia");
        map.put("FSM", "Micronesia");
        map.put("MD", "Moldova");
        map.put("MDA", "Moldova");
        map.put("MC", "Monaco");
        map.put("MCO", "Monaco");
        map.put("MN", "Mongolia");
        map.put("MNG", "Mongolia");
        map.put("ME", "Montenegro");
        map.put("MNE", "Montenegro");
        map.put("MS", "Montserrat");
        map.put("MSR", "Montserrat");
        map.put("MA", "Morocco");
        map.put("MAR", "Morocco");
        map.put("MZ", "Mozambique");
        map.put("MOZ", "Mozambique");
        map.put("MM", "Myanmar");
        map.put("MMR", "Myanmar");

        map.put("NA", "Namibia");
        map.put("NAM", "Namibia");
        map.put("NR", "Nauru");
        map.put("NRU", "Nauru");
        map.put("NP", "Nepal");
        map.put("NPL", "Nepal");
        map.put("NL", "Netherlands");
        map.put("NLD", "Netherlands");
        map.put("AN", "Netherlands Antilles");
        map.put("ANT", "Netherlands Antilles");
        map.put("NC", "New Caledonia");
        map.put("NCL", "New Caledonia");
        map.put("NZ", "New Zealand");
        map.put("NZL", "New Zealand");
        map.put("NI", "Nicaragua");
        map.put("NIC", "Nicaragua");
        map.put("NE", "Niger");
        map.put("NER", "Niger");
        map.put("NG", "Nigeria");
        map.put("NGA", "Nigeria");
        map.put("NU", "Niue");
        map.put("NIU", "Niue");
        map.put("KP", "North Korea");
        map.put("PRK", "North Korea");
        map.put("MP", "Northern Mariana Islands");
        map.put("MNP", "Northern Mariana Islands");
        map.put("NO", "Norway");
        map.put("NOR", "Norway");

        map.put("OM", "Oman");
        map.put("OMN", "Oman");
        map.put("PK", "Pakistan");
        map.put("PAK", "Pakistan");
        map.put("PW", "Palau");
        map.put("PLW", "Palau");
        map.put("PS", "Palestine");
        map.put("PSE", "Palestine");
        map.put("PA", "Panama");
        map.put("PAN", "Panama");
        map.put("PG", "Papua New Guinea");
        map.put("PNG", "Papua New Guinea");
        map.put("PY", "Paraguay");
        map.put("PRY", "Paraguay");
        map.put("PE", "Peru");
        map.put("PER", "Peru");
        map.put("PH", "Philippines");
        map.put("PHL", "Philippines");
        map.put("PN", "Pitcairn");
        map.put("PCN", "Pitcairn");
        map.put("PL", "Poland");
        map.put("POL", "Poland");
        map.put("PT", "Portugal");
        map.put("PRT", "Portugal");
        map.put("PR", "Puerto Rico");
        map.put("PRI", "Puerto Rico");
        map.put("QA", "Qatar");
        map.put("QAT", "Qatar");
        map.put("CG", "Republic of the Congo");
        map.put("COG", "Republic of the Congo");
        map.put("RE", "Reunion");
        map.put("REU", "Reunion");
        map.put("RO", "Romania");
        map.put("ROU", "Romania");
        map.put("RU", "Russia");
        map.put("RUS", "Russia");
        map.put("RW", "Rwanda");
        map.put("RWA", "Rwanda");

        map.put("BL", "Saint Barthelemy");
        map.put("BLM", "Saint Barthelemy");
        map.put("SH", "Saint Helena");
        map.put("SHN", "Saint Helena");
        map.put("KN", "Saint Kitts and Nevis");
        map.put("KNA", "Saint Kitts and Nevis");
        map.put("LC", "Saint Lucia");
        map.put("LCA", "Saint Lucia");
        map.put("MF", "Saint Martin");
        map.put("MAF", "Saint Martin");
        map.put("PM", "Saint Pierre and Miquelon");
        map.put("SPM", "Saint Pierre and Miquelon");
        map.put("VC", "Saint Vincent and the Grenadines");
        map.put("VCT", "Saint Vincent and the Grenadines");
        map.put("WS", "Samoa");
        map.put("WSM", "Samoa");
        map.put("SM", "San Marino");
        map.put("SMR", "San Marino");
        map.put("ST", "Sao Tome and Principe");
        map.put("STP", "Sao Tome and Principe");
        map.put("SA", "Saudi Arabia");
        map.put("SAU", "Saudi Arabia");
        map.put("SN", "Senegal");
        map.put("SEN", "Senegal");
        map.put("RS", "Serbia");
        map.put("SRB", "Serbia");
        map.put("SC", "Seychelles");
        map.put("SYC", "Seychelles");
        map.put("SL", "Sierra Leone");
        map.put("SLE", "Sierra Leone");
        map.put("SG", "Singapore");
        map.put("SGP", "Singapore");
        map.put("SX", "Sint Maarten");
        map.put("SXM", "Sint Maarten");

        map.put("SK", "Slovakia");
        map.put("SVK", "Slovakia");
        map.put("SI", "Slovenia");
        map.put("SVN", "Slovenia");
        map.put("SB", "Solomon Islands");
        map.put("SLB", "Solomon Islands");
        map.put("SO", "Somalia");
        map.put("SOM", "Somalia");
        map.put("ZA", "South Africa");
        map.put("ZAF", "South Africa");
        map.put("KR", "South Korea");
        map.put("KOR", "South Korea");
        map.put("SS", "South Sudan");
        map.put("SSD", "South Sudan");
        map.put("ES", "Spain");
        map.put("ESP", "Spain");
        map.put("LK", "Sri Lanka");
        map.put("LKA", "Sri Lanka");
        map.put("SD", "Sudan");
        map.put("SDN", "Sudan");
        map.put("SR", "Suriname");
        map.put("SUR", "Suriname");
        map.put("SJ", "Svalbard and Jan Mayen");
        map.put("SJM", "Svalbard and Jan Mayen");
        map.put("SZ", "Swaziland");
        map.put("SWZ", "Swaziland");
        map.put("SE", "Sweden");
        map.put("SWE", "Sweden");
        map.put("CH", "Switzerland");
        map.put("CHE", "Switzerland");
        map.put("SY", "Syria");
        map.put("SYR", "Syria");

        map.put("TW", "Taiwan");
        map.put("TWN", "Taiwan");
        map.put("TJ", "Tajikistan");
        map.put("TJK", "Tajikistan");
        map.put("TZ", "Tanzania");
        map.put("TZA", "Tanzania");
        map.put("TH", "Thailand");
        map.put("THA", "Thailand");
        map.put("TG", "Togo");
        map.put("TGO", "Togo");
        map.put("TK", "Tokelau");
        map.put("TKL", "Tokelau");
        map.put("TO", "Tonga");
        map.put("TON", "Tonga");
        map.put("TT", "Trinidad and Tobago");
        map.put("TTO", "Trinidad and Tobago");
        map.put("TN", "Tunisia");
        map.put("TUN", "Tunisia");
        map.put("TR", "Turkey");
        map.put("TUR", "Turkey");
        map.put("TM", "Turkmenistan");
        map.put("TKM", "Turkmenistan");
        map.put("TC", "Turks and Caicos Islands");
        map.put("TCA", "Turks and Caicos Islands");
        map.put("TV", "Tuvalu");
        map.put("TUV", "Tuvalu");
        map.put("VI", "U.S. Virgin Islands");
        map.put("VIR", "U.S. Virgin Islands");
        map.put("UG", "Uganda");
        map.put("UGA", "Uganda");
        map.put("UA", "Ukraine");
        map.put("UKR", "Ukraine");
        map.put("AE", "United Arab Emirates");
        map.put("ARE", "United Arab Emirates");
        map.put("GB", "United Kingdom");
        map.put("GBR", "United Kingdom");
        map.put("US", "United States");
        map.put("USA", "United States");
        map.put("UY", "Uruguay");
        map.put("URY", "Uruguay");
        map.put("UZ", "Uzbekistan");
        map.put("UZB", "Uzbekistan");
        map.put("VU", "Vanuatu");
        map.put("VUT", "Vanuatu");
        map.put("VA", "Vatican");
        map.put("VAT", "Vatican");
        map.put("VE", "Venezuela");
        map.put("VEN", "Venezuela");
        map.put("VN", "Vietnam");
        map.put("VNM", "Vietnam");
        map.put("WF", "Wallis and Futuna");
        map.put("WLF", "Wallis and Futuna");
        map.put("EH", "Western Sahara");
        map.put("ESH", "Western Sahara");
        map.put("YE", "Yemen");
        map.put("YEM", "Yemen");
        map.put("ZM", "Zambia");
        map.put("ZMB", "Zambia");
        map.put("ZW", "Zimbabwe");
        map.put("ZWE", "Zimbabwe");

    }
}
